version: "3.8"

services:
  smtp:
    container_name: mail-service
    image: rnwood/smtp4dev
    ports:
      - ${MAILER_PORT:-2525}:25
      - 5000:80

  db:
    container_name: ${JOURNEY_DATABASE_NAME}
    image: "postgres:latest"
    ports:
      - ${JOURNEY_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}

 # to raise the dockerfile of the application
 # app:
 #   build: .
 #   ports:
 #     - "8080:8080"
 #   environment:
 #     JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-db}
 #     JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT:-5432}
 #     JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
 #     JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
 #     JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
 #     TERN_CONFIG: ${TERN_CONFIG}
 #     TERN_MIGRATIONS: ${TERN_MIGRATIONS}
 #   depends_on:
 #     - db
